spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audio_db
    username: doguyegin
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

audio:
  path: audio/
  output-path: output/ 